language: python

os:
 - linux
 - osx

python:
 - "2.7"

install:
 - ifmac () { if [[ $TRAVIS_OS_NAME == osx ]]; then eval $@; fi; }
 - iflin () { if [[ $TRAVIS_OS_NAME == linux ]]; then eval $@; fi; }
 - pip install .

script:
 - qpm --help

notifications:
  on_success: change
  on_failure: change
 
