language:
 - objective-c

os:
 - osx

python:
 - "2.7"

install:
 - ifmac () { if [[ $TRAVIS_OS_NAME == osx ]]; then eval $@; fi; }
 - iflin () { if [[ $TRAVIS_OS_NAME == linux ]]; then eval $@; fi; }
 - sudo pip install .
 - brew install jack
 - ifmac curl -L https://github.com/supercollider/supercollider/releases/download/Version-3.7.0-alpha0/SuperCollider-Mac.zip -o SuperCollider-Mac.zip
 - ifmac unzip -d . SuperCollider-Mac.zip

script:
 - jackd -d net &
 - qpm --help
 - ifmac qpm test.list --path ./SuperCollider/SuperCollider.app
 - ifmac qpm test.run "*:*" -o --path ./SuperCollider/SuperCollider.app

notifications:
  on_success: change
  on_failure: change
 
