language:
 - objective-c

os:
 - osx

python:
 - "2.7"

install:
 - ifmac () { if [[ $TRAVIS_OS_NAME == osx ]]; then eval $@; fi; }
 - iflin () { if [[ $TRAVIS_OS_NAME == linux ]]; then eval $@; fi; }
 - sudo pip install .
 - ifmac curl -s -L https://github.com/supercollider/supercollider/releases/download/Version-3.7.0-alpha0/SuperCollider-Mac.zip -o SuperCollider-Mac.zip
 - ifmac unzip -qq -d . SuperCollider-Mac.zip
 - qpm quark checkout CommonTests MachineListeningUnitTests MathLibTests --location $HOME/Quarks
 - ifmac qpm test.list -o --path ./SuperCollider/SuperCollider.app

script:
 - ifmac qpm test.run "*:*" -o --path ./SuperCollider/SuperCollider.app --include $HOME/Quarks

notifications:
  on_success: change
  on_failure: change
 
